### ISSUE TITLE
Does react-mark help on creating a flavored syntax?

### ISSUE THREAD

**Issue by andrerpena** [casesandberg/react-mark#1]
First.. Thanks for putting this together.
I'm writing a software documentation application in React and it's supposed to support flavored markdown. That is: What you write is basically markdown, but `@someSyntax { ... }` is treated differently. Example:

```
@mockup {
    textbox displayName:"Full name"
}
```

In the above example.. The whole `@mockup` syntax is used to setup a `Mockup` React component inside the markdown result. I will support multiple syntaxes like the above.

Can react-mark help me on that?

**Comment by casesandberg** [comment]
`react-mark` is currenlty using https://github.com/evilstreak/markdown-js to do markdown parsing which doesnt realy support custom transforms. You can, however, create a custom paragraph component that has your own regex to transform this into a component!
