### ISSUE TITLE
ReferenceError: window is not defined in Mark.js

### ISSUE THREAD

**Issue by donpinkus** [casesandberg/react-mark#3]
ReferenceError: window is not defined

Mark.render
`/node_modules/react-mark/lib/components/Mark.js:45:7`

**Comment by donpinkus** [comment]
Ah, this is only an issue when doing server side rendering

**Comment by casesandberg** [comment]
Ah, these are only for debugging anyways, I should have removed them. Thanks for bringing this to my attention!

**Comment by casesandberg** [comment]
Just published `react-mark@0.0.2` on npm with window removed!
