### ISSUE TITLE
Replace is not working

### ISSUE THREAD

**Issue by donpinkus** [casesandberg/react-mark#4]
This code doesn't seem to use the "replace" attribute. There doesn't end up being any `<div class="testWrapper">` in the result.

Anyone else having this experience?

MarkdownHeader.js

```
import React, { Component } from 'react';

export class MarkdownHeader extends Component {
  render() {
    const header = this.props.children[0];

    return (
      <div className="testWrapper">
        {header}
      </div>
    );
  }
}
```

SomeComponent.js

```
import React, { Component } from 'react';
import Markdown from 'react-mark';
import { MarkdownHeader } from 'components'; 

export default class SomeComponent extends Component {
  render() {
    const {repos, repoId} = this.props;
    const repo = this.getRepo(repos, repoId);

    return (
      <Markdown replace={{ h1: MarkdownHeader }}>
        # Test
      </Markdown>
    );
  }
}
```

**Comment by casesandberg** [comment]
The way it is set up now you need to replace the `header` component which handles all of the headers as you can see here. It is passed a `level` prop with the h number: https://github.com/casesandberg/react-mark/blob/master/src/components/basic/H.js

```
<Markdown replace={{ header: MarkdownHeader }}>
  # Test
</Markdown>
```

Do you think it would make more sense for each of the headers to be their own component?

**Comment by donpinkus** [comment]
Hmm interesting - I had tried it with headers originally (made more sense for my use) and wasn't getting any result. Or maybe I was doing something dumb like just using "header"? 

I think 'headers' is fine, the other markdown renderer I had worked with in the past also just did headers + level :)

**Comment by casesandberg** [comment]
Hmm, yeah let me know if it still doesnt work for you. It uses `replace.header` as you can see here: https://github.com/casesandberg/react-mark/blob/master/src/helpers/findComponent.js#L9

**Comment by casesandberg** [comment]
Closing this out, let me know if you have any more problems
