### ISSUE TITLE
emoji / hashtag support?

### ISSUE THREAD

**Issue by babsonmatt** [casesandberg/react-mark#5]
Any suggestions as to how one might go about adding support for things like emojis  / hashtags (or anything else that wouldn't reply on just replacing a preexisting component but actually parsing the markdown itself)?

Thanks!

**Comment by casesandberg** [comment]
Emojis should work out of the box. I just did a test and it works, let me know what you are seeing if you are having troubles. 

Custom parsing is totally do-able. Say you wanted to link all hashtags in your markdown to the twitter search result page for that hashtag. We are going to create a custom paragraph component that handles adding in the links:

```
class PWithHashtagLinks extends React.Component {
  render() {
    // find every hashtag and replace with a link
    let text = this.props.children.replace(/#(\S*)/g, '<a href="http://twitter.com/#!/search/$1">$1</a>');
    return <p>{ text }</p>;
  }
}
```

And then you just use the replace prop for `react-mark` to use your component when wrapping paragraphs:

```
<Markdown replace={{ p: PWithHashtagLinks }}>
I love #react
</Markdown>
```

returns:

```
>>   <p>I love #<a href="http://twitter.com/#!/search/react">react</a></p>
```
